import type { Metadata } from "next";
import { Inter, K2D } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = K2D({ subsets: ["thai"], weight: "300" });

export const metadata: Metadata = {
  title: "รายรับรายจ่าย",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
